# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

permalink: pretty

title: 2204 Rambots
email: contact@rambots.org
home_header: Inspiration Starts Here
description: >- # this means to ignore newlines until "baseurl:"
  Located in Hayward, California, the 2204 Rambots is a FIRST Robotics team that gives opportunities for students to 
  build up skills and knowledge in science and technology through engineering and partnerships with the community.
# TODO change URLs once domain is purchased
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rambots.org" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: frc2204
github_username: frc2204
# facebook_username: RambotsTeam2204
rss: RSS Feed
tba: 2204
first_num: 2204

docs_url: https://docs.rambots.org/

member_bio_length: 100

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  mentors:
    output: true
  leadership:
    output: true
  members:
    output: true
  alumni:
    output: true

defaults:
  - scope:
      path: ""
      type: "mentors"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "leadership"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "alumni"
    values:
      layout: "member"


exclude:
  - livereload.sh

